services:
  - type: web
    name: messengeragent
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FACEBOOK_PAGE_ACCESS_TOKEN
        sync: false
      - key: FACEBOOK_VERIFY_TOKEN
        sync: false
      - key: SHOP_NAME
        sync: false